FROM arm32v5/debian:bookworm
RUN apt-get update
RUN apt-get -yy install build-essential git meson cmake ninja-build nlohmann-json3-dev pkg-config libssl-dev
RUN git clone https://github.com/Habbie/voorkant-core #2
RUN cd voorkant-core && git checkout lvgl-linuxfb && git submodule init && git submodule update
RUN cd voorkant-core && LDFLAGS=-static LIBS=-latomic meson setup build --prefer-static -Dbuildtype=release
RUN cd voorkant-core && ninja -C build