FROM arm32v5/debian:bookworm
RUN apt-get update
RUN apt-get -yy install build-essential git cmake ninja-build nlohmann-json3-dev pkg-config libssl-dev
RUN apt-get -yy install python3-pip
RUN pip install --break-system-packages meson
